# .github/workflows/deploy-to-runpod.yml
name: Deploy to RunPod

on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: loglevel
        default: warning
      tags:

jobs:
  deploy_runpod:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Deploy to RunPod
      - name: Deploy to RunPod
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
          RUNPOD_TEMPLATE_ID: vpjlpywfj4
        run: |
           echo "Curl started"
           echo "$RUNPOD_API_KEY"
           echo "$RUNPOD_TEMPLATE_ID"
           
           # Define the payload for the RunPod API request
           # Make API call to RunPod to start the container
           curl -X POST https://api.runpod.io/graphql?api_key=${RUNPOD_API_KEY} \
           -H "content-type: application/json" \
           -d '{"query": " mutation { deployCpuPod( input: { cloudType: SECURE, containerDiskInGb: 10, dataCenterId: null, instanceId: \"cpu3c-2-4\", networkVolumeId: null, startJupyter: true, startSsh: true, templateId: \"${env.RUNPOD_TEMPLATE_ID}\", volumeKey: null, env: [{key: \"a\", value: \"1\"}, {key: \"b\", value: \"2\"}] }) { id, machineId }}"}'
